branch-defaults:
  default:
    environment: null
    group_suffix: null
global:
  application_name: BoardGameNight
  branch: null
  default_platform: IIS 10.0 running on 64bit Windows Server 2019
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
