deploy:
  runs-on: windows-latest
  needs: build
  environment:
    name: 'Production'
    url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: .net-app

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'BoardGameNight'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6CC4F9FC83A3470AAA19FE8FD4C0D3F5 }}
        package: .
        
    - name: Install EF Core tools
      run: dotnet tool install --global dotnet-ef

    - name: EF Core Database Update
      run: dotnet ef database update --project ./BoardGameNight/BoardGameNight.csproj --startup-project ./BoardGameNight/BoardGameNight.csproj
      env:
        ConnectionStrings__DefaultConnection: ${{ secrets.DEFAULT_CONNECTION }}
